In [11]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

In [12]:
A = [[1,  2,  3],
     [2, -4,  6],
     [3, -9, -3]]

A = np.array(A)
A

array([[ 1,  2,  3],
       [ 2, -4,  6],
       [ 3, -9, -3]])

In [13]:
L = np.array([[1,0,0],[2,1,0],[3,15/8,1]])
U = np.array([[1,2,3],[0,-8,0],[0,0,-12]])
U

array([[  1,   2,   3],
       [  0,  -8,   0],
       [  0,   0, -12]])

In [14]:
P, L, U= la.lu(A)
P,L,U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [0.66666667, 0.4       , 1.        ]]),
 array([[ 3. , -9. , -3. ],
        [ 0. ,  5. ,  4. ],
        [ 0. ,  0. ,  6.4]]))

In [15]:
P@L@U

array([[ 1.,  2.,  3.],
       [ 2., -4.,  6.],
       [ 3., -9., -3.]])