In [9]:
import numpy as np
from scipy import linalg
np.set_printoptions(suppress=True)

In [26]:
#A = np.array([[2,1],[3,1]])
e1 = np.array([1,0])
e2 = np.array([0,1])


In [22]:
v1 = np.array([1,3])
v2 = np.array([4,1])

print("Av1: ")
print(A.dot(v1))
print("Av2: ")
print(A.dot(v2))

Av1: 
[5 6]
Av2: 
[ 9 13]


In [19]:
B = np.array([[1,4],[3,1]])
print(B)
B_inv = linalg.inv(B)
(B.dot(B_inv))

[[1 4]
 [3 1]]


array([[1., 0.],
       [0., 1.]])

In [23]:
T = B.dot(A.dot(B_inv))
T

array([[0.09090909, 4.63636364],
       [0.27272727, 2.90909091]])

In [38]:
A = np.array([[1,2,-1,1,2],[3,-4,0,2,3],[0,2,1,0,4],[2,2,-3,2,0],[-2,6,-1,-1,-1]])

np.linalg.matrix_rank(A)
np.linalg.det(A)

-3.1554436208840535e-30

In [53]:
f = np.array([[1,1,0],[1,0,2],[3,4,1]]) #transformation f(x)

e1 = np.array([1,0,0]) #demonstrate that f(e1) is (1,1,3) and so on
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

#new basis vector
print(f.dot(e1))
print(f.dot(e2))
print(f.dot(e3))

v1 = np.array([2,3,3])
v2 = np.array([8,5,2])
v3 = np.array([1,0,5])

#print(f)
#print(e1,e2,e3)
#print(v1,v2,v3)

[1 1 3]
[1 0 4]
[0 2 1]


In [58]:
#transform vector with f
print("f(v1):", f.dot(v1))
print("f(v2):", f.dot(v2))
print("f(v3):", f.dot(v3))

f(v1): [ 5  8 21]
f(v2): [13 12 46]
f(v3): [ 1 11  8]
